### ISSUE TITLE
Link the APIS

### ISSUE THREAD

**Issue by nicnolen** [felipezintzun/watchopedia#11]
**To Do**
- Styling API
  - Bulma: https://bulma.io/documentation/overview/start/
- Server Side APIS
  - TvMaze: https://api.tvmaze.com/ (Felipe)
  - IMbD: https://imdb-api.com/api (Than)

**Comment by ThanNguyen1** [comment]
thinking of switching CSS api to Bulma since it's a bit easier to link. Just adding comments on the APIs I'll be linking
- https://api.tvmaze.com/
- https://imdb-api.com/api
- https://bulma.io/documentation/overview/start/

**Comment by nicnolen** [comment]
Linked Bulma through the HTML page and made fetch requests for imbd and TvMaze
