### ISSUE TITLE
Make the header

### ISSUE THREAD

**Issue by CRZCode5150** [felipezintzun/watchopedia#6]
**To-Do**
- Add in the hero image (Judy)
- Add in the title (Nicholas)
- Add in the nav-bar (contains API links to TV shows and movies) (Christian)
- Add in the input element (Nicholas)

**Comment by nicnolen** [comment]
**Add in the input element**
- Made a datalist to create a drop-down menu with predefined options for the input element
- Populate the datalist options dynamically with APIs
- Styled using Bulma API and custom CSS
